name: nextest

on:
  workflow_run:
    workflows: [build and check]
    types: [completed]
    branches: [main]

jobs:
  nextest:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Configure Nix
        run: |
          mkdir -p ~/.config/nix

          cat > ~/.config/nix/nix.conf <<EOF
          experimental-features = nix-command flakes
          substituters = https://devcache.lautaroacosta.com/dev-cache https://cache.nixos.org/
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= dev-cache:lV4Nej+9+n3g2uAgGKIBpaffUvzKR1essUx1opU33/0=
          EOF

      - name: Run nextest
        run: nix develop --command cargo nextest run
