[package]
name = "poster"
edition = "2024"
version.workspace = true
rust-version.workspace = true

[dependencies]
axum = { version = "0.8.8", features = ["macros","multipart"] }
axum-extra = { version = "0.12.3", features = ["cookie", "typed-header"] }
color-eyre = "0.6.5"
config = "0.15.19"
eyre = "0.6.12"
http = "1.4.0"
secrecy = { version = "0.10.3", features = ["serde"] }
time = { version = "0.3.44", features = ["formatting", "serde"] }
tokio = { version = "1.48.0", features = ["full"] }
tower = "0.5.2"
tracing.workspace = true
tower-http = { version = "0.6.8", features = ["cors", "fs", "normalize-path", "trace"] }
tracing-bunyan-formatter = "0.3.10"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
uuid = { workspace = true, features = ["serde"] }
serde.workspace = true
opentelemetry-otlp = {version = "0.31.0", features = ["serialize"] }
facebook_graph_api = { path = "../facebook_graph_api/", features = ["axum","time"]}
auth = { path = "../auth" }
thiserror = "2.0.17"
serde_json.workspace = true
sqlx = { version = "0.8", features = [
  "runtime-tokio",
  "sqlite",
  "time",
  "migrate",
  "uuid"
] }
tracing-log = "0.2.0"
reqwest = { workspace = true, features = ["cookies"] }
moka = { version = "0.12.12", features = ["future", "log"] }
base64 = "0.22.1"
image = "0.25.9"
aws-sdk-s3 = "1.119.0"
opentelemetry = "0.31.0"
tracing-opentelemetry = "0.32.0"
# opentelemetry-jaeger-propagator = "0.31.0"
opentelemetry_sdk = { version = "0.31.0", features = ["rt-tokio"] }
argon2 = "0.5.3"
tower-sessions = "0.14.0"
tower-sessions-sqlx-store = { version = "0.15.0", features = ["sqlite"] }
aws-config = { version = "1.8.12", features = ["behavior-version-latest"] }


[dev-dependencies]
tempfile = "3.24.0"
expect-test = "1.5.1"
wiremock = "0.6.5"
pretty_assertions = "1.4.1"
