run: 
    cargo run | bunyan

check_scripts:
    shellcheck -f diff ./crates/poster/setup/*

start_db:
    ./setup/setup_db.sh

migrate:
    SKIP_DOCKER=true ./setup/setup_db.sh


test:
    cargo nextest run --all-features

check:
    cargo check --all-features
